[site]
name = "Joseph R. Hobbs"
style = "tech"
icon = "media/favicon.ico"

[menu]
names = ["Home", "About", "Projects", "Contact"]
links = ["/", "/about", "/projects", "/contact"]

[media]
include = [
    "code.jpg",
]