[site]
name = "Joseph R. Hobbs"
style = "tech"
icon = "media/favicon.ico"

[menu]
names = ["Home", "About", "Projects", "Contact"]
links = ["/", "/about", "/projects", "/contact"]

[analytics]
tag = "analytics-tag.html"

[media]
include = [
    "code.jpg",
    "me.jpg",
    "blotch.png",
    "blotch-example.png",
    "bwb.jpg",
    "bwb-example.jpg",
    "bwb-part-ii-a.png",
    "bwb-part-ii-b.png",
    "bwb-part-iii.png",
    "bwb-simulation.png",
    "wifi.png",
    "key.jpg",
    "vlm-wing.jpg",
    "rsa-block-diagram.png",
    "airplane-propeller.jpg",
    "mosfet.jpg",
    "dna-rna.png",
]